### ISSUE TITLE
Installing via pip throws an exception

### ISSUE THREAD

**Issue by aodj** [dohop/supervisor-logstash-notifier#8]
When running `pip install supervisor-logstash-notifier` the following exception is thrown: 

```bash
(venv2) Alexanders-Mac-mini:temp alexander$ pip install supervisor-logstash-notifier
Collecting supervisor-logstash-notifier
  Downloading supervisor-logstash-notifier-0.2.3.tar.gz
Collecting python-logstash==0.4.6 (from supervisor-logstash-notifier)
  Downloading python-logstash-0.4.6.tar.gz
Collecting six==1.10.0 (from supervisor-logstash-notifier)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting argparse (from supervisor-logstash-notifier)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Building wheels for collected packages: supervisor-logstash-notifier, python-logstash
  Running setup.py bdist_wheel for supervisor-logstash-notifier ... error
  Complete output from command /Users/alex/Documents/github/dohop/temp/venv2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/pn/pt4ccg0j6n11yvnlllx_xbpr0000gp/T/pip-build-jFPhgH/supervisor-logstash-notifier/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/pn/pt4ccg0j6n11yvnlllx_xbpr0000gp/T/tmpgIFRo0pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/logstash_notifier
  copying logstash_notifier/__init__.py -> build/lib/logstash_notifier
  installing to build/bdist.macosx-10.11-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.11-x86_64
  creating build/bdist.macosx-10.11-x86_64/wheel
  creating build/bdist.macosx-10.11-x86_64/wheel/logstash_notifier
  copying build/lib/logstash_notifier/__init__.py -> build/bdist.macosx-10.11-x86_64/wheel/logstash_notifier
  running install_egg_info
  running egg_info
  writing requirements to supervisor_logstash_notifier.egg-info/requires.txt
  writing supervisor_logstash_notifier.egg-info/PKG-INFO
  writing top-level names to supervisor_logstash_notifier.egg-info/top_level.txt
  writing dependency_links to supervisor_logstash_notifier.egg-info/dependency_links.txt
  writing entry points to supervisor_logstash_notifier.egg-info/entry_points.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'supervisor_logstash_notifier.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'supervisor_logstash_notifier.egg-info/SOURCES.txt'
  Copying supervisor_logstash_notifier.egg-info to build/bdist.macosx-10.11-x86_64/wheel/supervisor_logstash_notifier-0.2.3-py2.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/pn/pt4ccg0j6n11yvnlllx_xbpr0000gp/T/pip-build-jFPhgH/supervisor-logstash-notifier/setup.py", line 43, in <module>
      tests_require=test_requirements.read().splitlines(),
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Users/alex/Documents/github/dohop/temp/venv2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/Users/alex/Documents/github/dohop/temp/venv2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 399, in egg2dist
      distribution=self.distribution)
    File "/Users/alex/Documents/github/dohop/temp/venv2/lib/python2.7/site-packages/wheel/metadata.py", line 176, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/Users/alex/Documents/github/dohop/temp/venv2/lib/python2.7/site-packages/wheel/metadata.py", line 231, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/Users/alex/Documents/github/dohop/temp/venv2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2833, in parse
      req, = parse_requirements(s)
  ValueError: need more than 0 values to unpack

  ----------------------------------------
  Failed building wheel for supervisor-logstash-notifier
  Running setup.py clean for supervisor-logstash-notifier
  Running setup.py bdist_wheel for python-logstash ... done
  Stored in directory: /Users/alex/Library/Caches/pip/wheels/ca/41/e9/9520418d719c32a71b98a707ae3b09bd71604d8f64c8bd96d2
Successfully built python-logstash
Failed to build supervisor-logstash-notifier
Installing collected packages: python-logstash, six, argparse, supervisor-logstash-notifier
  Running setup.py install for supervisor-logstash-notifier ... done
Successfully installed argparse-1.4.0 python-logstash-0.4.6 six-1.10.0 supervisor-logstash-notifier-0.2.3
```

**Comment by aodj** [comment]
After fixing the `test_requirements.txt` file too, and updating the version number I can install from pypi without a problem.
